import Head from "next/head";
import React, { useContext, useEffect } from "react";
import Header from "../components/Header";
import UserContext from "../context/UserContext";
import { FcGoogle } from "react-icons/fc";
import { FaStopwatch } from "react-icons/fa";
import { getAuth, GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import { app } from "../utils/firebase";
import toast from "react-hot-toast";
import useCheckAuth from "../hooks/useCheckAuth";
import Loader from "../components/Loader";
import { useRouter } from "next/router";

const auth = getAuth(app);
const provider = new GoogleAuthProvider();

const Login = () => {
  const userContext = useContext(UserContext);
  const router = useRouter();
  const { user, loading } = useCheckAuth();

  const handleSignIn = async () => {
    try {
      const result = await signInWithPopup(auth, provider);
      const { displayName, email, photoURL } = result.user;
      if (email && displayName && photoURL) {
        userContext?.setUser({ displayName, email, photoURL });
        toast.success(`welcome ${displayName}`);
        router.push("/");
      } else {
        toast.success("login error");
      }
    } catch (error: any) {
      toast.error(error.message);
    }
  };

  return (
    <section className="relative min-h-[100vh] bg-bgDark text-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <Loader />}
      <Header />
      <div className="container min-h-[calc(100vh - 80px)] flex items-center justify-center">
        <main className="border border-borderColor w-[400px] max-w-[100%] rounded-xl py-12 px-8 flex flex-col items-center gap-2 mt-6">
          <FaStopwatch className="text-gray-300 text-8xl" />
          <h1 className="text-3xl text-gray-300">Pomodoro</h1>
          <p className="text-gray-400 mb-6">for getting started click below</p>
          <button
            onClick={handleSignIn}
            className="btn-primary flex items-center gap-2 text-xl bg-gray-200 hover:bg-gray-300 active:scale-[0.98] active:transition-none"
          >
            <FcGoogle className="text-2xl" />
            Continue With Google
          </button>
        </main>
      </div>
    </section>
  );
};

export default Login;
